# Generated by Django 4.2.16 on 2024-10-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stoma", "0002_userdata_rename_doctor_id_patient_doctor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="card_comment",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="reception_comment",
        ),
        migrations.AddField(
            model_name="patient",
            name="days_count",
            field=models.IntegerField(null=True),
        ),
    ]
