# Generated by Django 4.2.16 on 2024-10-27 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stoma", "0003_remove_patient_card_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stoma.userdata"
                    ),
                ),
            ],
        ),
    ]
